version: '3.8'

services:
  infinite-library:
    build:
      context: .
      dockerfile: site/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - book-collector
    volumes:
      - ./site/assets:/usr/share/nginx/html/assets

  book-collector:
    build:
      context: book_collector
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
    volumes:
      - pdf_data:/data
    env_file:
      - book_collector/.env

volumes:
  pdf_data: 