version: '3.8'

services:
  book-collector:
    build:
      context: book_collector
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - CORS_ALLOW_ORIGIN=http://localhost
    volumes:
      - pdf_data:/data
    env_file:
      - book_collector/.env
    networks:
      - infinite-library-network

volumes:
  pdf_data: 

networks:
  infinite-library-network:
